version: "3.9"

services:
  backend:
    build: .
    container_name: study-backend
    env_file: .env
    ports:
      - "8000:8000"    # host:container
    restart: always
    # If you want logs on host, you can later add:
    # volumes:
    #   - ./logs:/app/logs